### ISSUE TITLE
This seems to have been patched on the latest versions.

### ISSUE THREAD

**Issue by SpidFightFR** [Weather-OS/BRTXOnLinux#2]
On the latest version of Minecraft education as of 12/30/2023, we're greeted by a black screen :

![image](https://github.com/Weather-OS/BRTXOnLinux/assets/60798703/1d99b6e2-266d-4850-8fac-4e6196689d7f)

**Comment by Weather-OS** [comment]
You may only move the `data/resource_packs/education/ui` folder to your Minecraft installation

**Comment by SpidFightFR** [comment]
> You may only move the `data/resource_packs/education/ui` folder to your Minecraft installation

Sorry to disturb.
It worked now i get a display !

However there are no "play" button...
![image](https://github.com/Weather-OS/BRTXOnLinux/assets/60798703/38ddba4c-e1dc-481b-ba46-c6908999c204)

**Comment by Weather-OS** [comment]
Ah shucks. Well I’ll see what I can do. Try resizing the window maybe that’ll do the trick.

**Comment by SpidFightFR** [comment]
> Ah shucks. Well I’ll see what I can do. Try resizing the window maybe that’ll do the trick.

I tried doing that, even enabled gamescome, nothing changes. Was the button already ingame or a patch from you?

**Comment by Weather-OS** [comment]
Here, try this instead
[education.zip](https://github.com/Weather-OS/BRTXOnLinux/files/13806041/education.zip)

**Comment by SpidFightFR** [comment]
> Here, try this instead [education.zip](https://github.com/Weather-OS/BRTXOnLinux/files/13806041/education.zip)

Thanks,  it works !

**Comment by SpidFightFR** [comment]
Note: the version of VKD3D you provide doesn't seem to be necessary, i use mainstream VKD3D Proton 2.11.1 and it runs as well. On top of that, it doesn't require any environment variable (like `VKD3D_CONFIG=dxr11`).
